In [34]:
import sys
import yaml
import os
import pandas as pd
from sklearn.datasets import make_classification
sys.path.append(os.path.abspath(".."))

In [33]:

# Импортируем функцию для определения корня проекта
sys.path.append(os.path.abspath("../scripts"))
from auxiliary_functions import get_project_root

# Добавляем корень проекта в sys.path
sys.path.append(get_project_root())

from scripts.auxiliary_functions import get_project_paths

In [29]:
project_root = get_project_root()
params_path = os.path.join(project_root, "params.yaml")

with open(params_path, "r") as f:
    params = yaml.safe_load(f)
    paths = get_project_paths()

# Часть 1. Тесты на "идеально сгенерированных данных"

## Загружаем сгенерированные данные для идеального теста по регрессии

Принцип генерации данных

x1 = np.random.normal(0, 1, n_samples)
x2 = np.random.normal(0, 1, n_samples)
x3 = np.random.uniform(1, 2, n_samples)  
x4 = np.random.normal(0, 1, n_samples)
x5 = np.random.normal(0, 1, n_samples)
x6 = np.random.normal(0, 1, n_samples)

x7 = x1 + x2
x8 = np.log(x3)
x9 = x7 * np.sin(x6)
x10 = 20 * x1 + x2 / x3

X = np.stack([x1, x2, x3, x4, x5, x6, x7, x8, x9, x10], axis=1)

# Целевая переменная: функция + шум
y = np.sin(X[:, 0]) + np.sin(X[:, 1]) + np.random.normal(0, noise_std, n_samples)

In [31]:
syntetic_df = pd.read_csv(paths['raw_dir']/"synthetic_regression.csv")

In [32]:
syntetic_df

,Unnamed: 0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
0,0,0.496714,1.399355,1.407106,0.573128,-0.164335,0.486185,1.896070,0.341535,0.885950,10.928775,1.771709
1,1,-0.138264,0.924634,1.066010,-1.785866,0.212093,-1.949372,0.786369,0.063923,-0.730688,-1.897908,0.634759
2,2,0.647689,0.059630,1.348821,-0.359630,-0.993359,-2.050357,0.707319,0.299231,-0.627532,12.997980,0.713952
3,3,1.523030,-0.646937,1.110998,0.301107,-1.015879,0.739180,0.876093,0.105259,0.590209,29.878295,0.331178
4,4,-0.234153,0.698223,1.808235,0.183835,-1.388543,0.507020,0.464070,0.592351,0.225341,-4.296932,0.440361
...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,-0.281100,1.070150,1.342645,-0.412414,-0.399878,-2.506572,0.789050,0.294642,-0.468060,-4.824960,0.554471
996,996,1.797687,-0.026521,1.864659,0.257199,-0.114641,0.297462,1.771165,0.623078,0.519119,35.939507,1.036858
997,997,0.640843,-0.881875,1.154925,-0.240665,0.264268,0.139498,-0.241032,0.144036,-0.033514,12.053280,-0.234787
998,998,-0.571179,-0.163067,1.082737,0.007880,-0.150117,-0.284837,-0.734246,0.079492,0.206324,-11.574186,-0.722990
999,999,0.572583,-0.744903,1.484538,-0.325611,-1.264006,-0.106194,-0.172320,0.395104,0.018265,10.949882,0.003827

### Сравнение резульаттов

## Загружаем сгенерированные данные для идеального теста по классификации

In [39]:
# Генерация данных: 10 признаков, 2 класса, 5 информативных, 2 редундантных (зависимых), 3 шумовых
X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=5,
    n_redundant=2,
    n_repeated=0,
    n_classes=2,
    random_state=42
)

X = pd.DataFrame(X, columns=[f"feature_{i}" for i in range(X.shape[1])])
y = pd.Series(y, name="target")

# Объединяем X и y
new = pd.concat([X, y], axis=1)

# Сохраняем в CSV
new.to_csv(paths['raw_dir']/"synthetic_dataset.csv", index=False)

new

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,target
0,1.125100,1.178124,0.493516,0.790880,-0.614278,1.347020,1.419515,1.357325,0.966041,-1.981139,1
1,-0.564641,3.638629,-1.522415,-1.541705,1.616697,4.781310,3.190292,-0.890254,1.438826,-3.828748,0
2,0.516313,2.165426,-0.628486,-0.386923,0.492518,1.442381,1.332905,-1.958175,-0.348803,-1.804124,0
3,0.537282,0.966618,-0.115420,0.670755,-0.958516,0.871440,0.508186,-1.034471,-1.654176,-1.910503,1
4,0.278385,1.065828,-1.724917,-2.235667,0.715107,0.731249,-0.674119,0.598330,-0.524283,1.047610,0
...,...,...,...,...,...,...,...,...,...,...,...
995,-0.906303,-0.527162,-1.511787,-1.697166,-0.585131,0.160046,-2.225249,1.480886,-0.934154,1.151678,0
996,1.225603,-1.389881,-0.406775,-1.606446,2.500944,-1.089977,0.452517,-1.765429,1.297249,4.705105,1
997,1.650153,-0.692165,-2.049206,-1.610471,0.119157,-0.876080,-1.368269,-1.302577,-1.285505,3.328569,1
998,-1.186603,-1.414598,-0.121520,-1.440709,1.630283,-2.034632,-1.537456,-1.421465,-0.028340,3.413932,1
999,0.788676,-0.222547,0.328570,-1.654945,0.764075,0.620435,-0.132118,-1.291040,-2.338172,2.036021,0